import React from 'react';
import ReactDOM from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Registers the service worker generated by vite-plugin-pwa.
// New versions activate automatically on next load; no user prompt needed.
if ('serviceWorker' in navigator) {
  registerSW({ immediate: true });
}
