import React from 'react';
import ReactDOM from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Registers the service worker generated by vite-plugin-pwa.
//
// registerType: 'autoUpdate' (see vite.config.js) means a new version
// activates and reloads the page automatically — no "update available"
// prompt, no need to uninstall/reinstall the app. The piece browsers don't
// do aggressively on their own is *checking* for a new service-worker file
// while the app is already open (installed PWAs can stay open for days),
// so we trigger that check ourselves whenever the app regains focus, plus
// on an hourly timer as a backstop.
if ('serviceWorker' in navigator) {
  const updateSW = registerSW({
    immediate: true,
    onRegisteredSW(swScriptUrl, registration) {
      if (!registration) return;

      const checkForUpdate = () => registration.update().catch(() => {});

      // Check immediately, then whenever the installed app is brought back
      // to the foreground (the most common moment a stale version is seen).
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState === 'visible') checkForUpdate();
      });
      window.addEventListener('focus', checkForUpdate);

      // Backstop for long-running sessions that never lose focus.
      setInterval(checkForUpdate, 60 * 60 * 1000);
    },
  });
}
